### ISSUE TITLE
java.lang.NoClassDefFoundError: backtype/storm/metric/api/IMetricsConsumer

### ISSUE THREAD

**Issue by xiamx** [verisign/storm-graphite#35]
I followed installation instruction from the README file, using graphite consummer, though I got this error. 

```
java.lang.NoClassDefFoundError: backtype/storm/metric/api/IMetricsConsumer
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_101]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_101]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_101]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_101]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_101]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_101]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_101]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_101]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_101]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_101]
	at org.apache.storm.metric.MetricsConsumerBolt.prepare(MetricsConsumerBolt.java:43) ~[storm-core-1.0.1.jar:1.0.1]
	at org.apache.storm.daemon.executor$fn__7953$fn__7966.invoke(executor.clj:792) ~[storm-core-1.0.1.jar:1.0.1]
	at org.apache.storm.util$async_loop$fn__625.invoke(util.clj:482) [storm-core-1.0.1.jar:1.0.1]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.ClassNotFoundException: backtype.storm.metric.api.IMetricsConsumer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
	... 19 more
```

**Comment by xiamx** [comment]
nvm mybad, I'm build an older version
